export const mockEvents = [
  {
    id: 1,
    title: 'Birthday Party',
    description: 'A birthday celebration with friends and family.',
    date: 'Oct 12, 2026',
    time: '2:00 PM',
    rawDate: '2026-10-12',
    rawTime: '14:00',
    location: 'Nairobi',
    maxGuests: 50,
    tasksRemaining: 8,
    guests: 25,
    emoji: '🎈',
    color: 'purple',
  },
  {
    id: 2,
    title: 'Tech Meetup',
    description: 'A gathering for developers to share ideas and network.',
    date: 'Oct 20, 2026',
    time: '10:00 AM',
    rawDate: '2026-10-20',
    rawTime: '10:00',
    location: 'Campus',
    maxGuests: 60,
    tasksRemaining: 3,
    guests: 42,
    emoji: '💻',
    color: 'blue',
  },
  {
    id: 3,
    title: 'Team Building',
    description: 'Outdoor activities to strengthen team collaboration.',
    date: 'Nov 5, 2026',
    time: '9:00 AM',
    rawDate: '2026-11-05',
    rawTime: '09:00',
    location: 'Karen',
    maxGuests: 30,
    tasksRemaining: 5,
    guests: 18,
    emoji: '🤝',
    color: 'green',
  },
  {
    id: 4,
    title: 'Workshop',
    description: 'A hands-on session covering practical skills.',
    date: 'Nov 15, 2026',
    time: '1:00 PM',
    rawDate: '2026-11-15',
    rawTime: '13:00',
    location: 'Nairobi',
    maxGuests: 20,
    tasksRemaining: 4,
    guests: 12,
    emoji: '🛠️',
    color: 'orange',
  },
]
